# version: "3.8"
services:
    connector-ng-db:
        container_name: mysql
        # can be replaced with appropriate database image. e.g. postgres
        image: mysql:8
        restart: always
        environment:
            # can be replaced with appropriate database env. e.g. POSTGRES_PASSWORD, POSTGRES_USER ...
            MYSQL_DATABASE: connector
            MYSQL_USER: connector
            MYSQL_PASSWORD: connector
            MYSQL_ROOT_PASSWORD: connector
        ports:
            - "40000:3306"
        expose:
            - "3306"
        healthcheck:
            test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
            interval: 3s
            retries: 5
            timeout: 5s
        volumes:
            # based on your DBMS, initial scripts can be found in documentation/database-scripts/initial
            # copy and place them in sql folder
            # - ./sql/:/docker-entrypoint-initdb.d/
            - connector-ng-mysql-data:/var/lib/mysql
volumes:
    connector-ng-mysql-data:
