[versions]
# apache
apache-commons-lang3 = "3.20.0"
apache-commons-io = "2.21.0"
apache-cxf = "4.1.0"
apache-tika = "3.3.1"
apache-wss4j = "3.0.5" # do not migrate to 4.x series due to xmlsec 4.x serie clash
apache-xmlsec = "3.0.5" # keep this due to limitation of DSS library
# jakarta
jakarta-annotation = "3.0.0"
jakarta-activation = "2.1.4"
jakarta-validation = "3.1.1"
jakarta-jms-api = "3.1.0"
jakarta-jws-api = "3.0.0"
jakarta-mail = "2.0.2"
jakarta-xml-bind-api = "4.0.2"
jakarta-xml-ws-api = "4.0.2"
# jaxb
jaxb-impl = "4.0.6"
jaxb-xjc = "4.0.9"
# spring boot
spring-boot = "4.0.2"
spring-doc = "3.0.1"
s3 = "2.41.30"
# dbms
h2 = "2.4.240"
mysql = "8.0.33"
mariadb = "3.5.9"
postgresql = "42.7.11"
# jta
narayana = "4.0.0"
agroal = "3.0"
messaginghub = "3.2.2"
# other
dss-tool = "6.1"
itextpdf = "9.5.0"
jackson-databind = "2.21.0"
lombok = "1.18.42"
micrometer = "1.6.2"
okhttp = "5.3.2"
slf4j-api = "2.0.17"
# tests
assertj = "3.27.7"
junit = "5.10.0"
minio = "8.6.0"
minio-container = "2.0.1"
mockito = "5.21.0"

[libraries]
# apache
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons-lang3" }
apache-commons-io = { module = "commons-io:commons-io", version.ref = "apache-commons-io" }
apache-cxf-bom = { module = "org.apache.cxf:cxf-bom", version.ref = "apache-cxf" }
apache-tika = { module = "org.apache.tika:tika-core", version.ref = "apache-tika" }
apache-wss4j-common = { module = "org.apache.wss4j:wss4j-ws-security-common", version.ref = "apache-wss4j"}
apache-wss4j-dom = { module = "org.apache.wss4j:wss4j-ws-security-dom", version.ref = "apache-wss4j"}
apache-xmlsec = { module = "org.apache.santuario:xmlsec", version.ref = "apache-xmlsec"}
# jakarta
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jakarta-activation = { module = "jakarta.activation:jakarta.activation-api", version.ref = "jakarta-activation" }
jakarta-validation = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
jakarta-jms-api = { module = "jakarta.jms:jakarta.jms-api", version.ref = "jakarta-jms-api" }
jakarta-jws-api = { module = "jakarta.jws:jakarta.jws-api", version.ref = "jakarta-jws-api" }
jakarta-mail = { module = "com.sun.mail:jakarta.mail", version.ref = "jakarta-mail" }
jakarta-xml-bind-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakarta-xml-bind-api" }
jakarta-xml-ws-api = { module = "jakarta.xml.ws:jakarta.xml.ws-api", version.ref = "jakarta-xml-ws-api" }
# jaxb
jaxb-impl = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "jaxb-impl" }
jaxb-xjc = { module = "org.glassfish.jaxb:jaxb-xjc", version.ref = "jaxb-xjc" }
# spring + boot
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-doc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-doc"}
s3 = { module = "software.amazon.awssdk:s3", version.ref = "s3"}
# dbms
h2 = { module = "com.h2database:h2", version.ref = "h2" }
mysql = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
mariadb = { module = "org.mariadb.jdbc:mariadb-java-client", version.ref = "mariadb" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
# narayana
narayana = { module = "dev.snowdrop:narayana-spring-boot-starter", version.ref = "narayana" }
agroal = { module = "io.agroal:agroal-spring-boot-starter", version.ref = "agroal" }
messaginghub = { module = "org.messaginghub:pooled-jms", version.ref = "messaginghub" }
# other
dss-tool = { module = "eu.europa.ec.joinup.sd-dss:dss-bom", version.ref = "dss-tool" }
itextpdf = { module = "com.itextpdf:itext7-core", version.ref = "itextpdf" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-databind" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
micrometer = { module = "io.micrometer:micrometer-tracing-bridge-brave", version.ref = "micrometer" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
# test
minio = { module = "io.minio:minio", version.ref = "minio" }
minio-container = { module = "org.testcontainers:testcontainers-minio", version.ref = "minio-container" }
mockito = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
