[versions]
apache-commons = "3.20.0"
jakarta-annotation = "3.0.0"
jakarta-validation = "3.1.1"
jakarta-jms-api = "3.1.0"
lombok = "1.18.42"
micrometer = "1.6.2"
slf4j-api = "2.0.17"
spring-boot = "4.0.2"
spring-doc = "3.0.1"
s3 = "2.41.30"
# dbms
h2 = "2.4.240"
mysql = "8.0.33"
# tests
assertj = "3.27.7"
junit = "5.10.0"
mockito = "5.21.0"

[libraries]
apache-commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "apache-commons" }
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
jakarta-validation = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation" }
jakarta-jms-api = { module = "jakarta.jms:jakarta.jms-api", version.ref = "jakarta-jms-api" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
micrometer = { module = "io.micrometer:micrometer-tracing-bridge-brave", version.ref = "micrometer" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j-api" }
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-doc = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "spring-doc"}
s3 = { module = "software.amazon.awssdk:s3", version.ref = "s3"}
# dbms
h2 = { module = "com.h2database:h2", version.ref = "h2" }
mysql = { module = "mysql:mysql-connector-java", version.ref = "mysql" }
# test
mockito = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
