create table connector_business_domains
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone not null,
    updated_at  timestamp(6) with time zone not null,
    description varchar(255),
    enabled     boolean,
    identifier  varchar(255)                not null
        constraint ukmy79mo8v7caynl1438igqdoym
            unique,
    source      varchar(255)
        constraint connector_business_domains_source_check
            check ((source)::text = ANY
                   ((ARRAY ['DATABASE'::character varying, 'IMPLEMENTATION'::character varying, 'ENVIRONMENT'::character varying, 'APPLICATION'::character varying])::text[])),
    uuid        varchar(255)                not null
        constraint ukn51pa7n16yduxrhwe74jqshnm
            unique
);

alter table connector_business_domains
    owner to connector;

create table connector_message_transport_steps
(
    id                             bigint generated by default as identity
        primary key,
    created_at                     timestamp(6) with time zone not null,
    updated_at                     timestamp(6) with time zone not null,
    identifier                     varchar(255)                not null,
    link_partner_name              varchar(255),
    number_of_attempts             integer                     not null,
    remote_system_identifier       varchar(255),
    status                         varchar(255)                not null
        constraint connector_message_transport_steps_status_check
            check ((status)::text = ANY
                   ((ARRAY ['DELIVERED'::character varying, 'FAILED'::character varying, 'SUBMITTED'::character varying, 'DOWNLOADED'::character varying, 'READY_FOR_DOWNLOAD'::character varying])::text[])),
    transported_message            varchar(5000000)            not null,
    transported_message_identifier varchar(255)                not null
);

alter table connector_message_transport_steps
    owner to connector;

create table connector_message_transport_step_statuses
(
    id                bigint generated by default as identity
        primary key,
    created_at        timestamp(6) with time zone not null,
    updated_at        timestamp(6) with time zone not null,
    status            varchar(255)                not null
        constraint connector_message_transport_step_statuses_status_check
            check ((status)::text = ANY
                   ((ARRAY ['DELIVERED'::character varying, 'FAILED'::character varying, 'SUBMITTED'::character varying, 'DOWNLOADED'::character varying, 'READY_FOR_DOWNLOAD'::character varying])::text[])),
    transport_step_id bigint
        constraint fk6ke4gt642ivtvi0f6c53hmuoo
            references connector_message_transport_steps
);

alter table connector_message_transport_step_statuses
    owner to connector;

create table connector_messages
(
    id                                      bigint generated by default as identity
        primary key,
    created_at                              timestamp(6) with time zone not null,
    updated_at                              timestamp(6) with time zone not null,
    backend_message_identifier              varchar(255),
    backend_name                            varchar(255),
    confirmed_at                            timestamp(6) with time zone,
    deleted_at                              timestamp(6) with time zone,
    delivered_to_link_partner_at            timestamp(6) with time zone,
    direction                               varchar(255)                not null
        constraint connector_messages_direction_check
            check ((direction)::text = ANY
                   ((ARRAY ['BACKEND_TO_GATEWAY'::character varying, 'GATEWAY_TO_BACKEND'::character varying])::text[])),
    gateway_name                            varchar(255),
    identifier                              varchar(255)                not null,
    reference_to_backend_message_identifier varchar(255),
    rejected_at                             timestamp(6) with time zone,
    business_domain_id                      bigint                      not null
        constraint fka44v5lab5jt09sum4j9xfrlen
            references connector_business_domains
);

alter table connector_messages
    owner to connector;

create table connector_message_attachments
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6) with time zone not null,
    updated_at   timestamp(6) with time zone not null,
    content_type varchar(255)                not null,
    description  varchar(255)                not null,
    identifier   varchar(255)                not null
        constraint ukqkwekyau6mx7fqymuavj4bkqw
            unique,
    name         varchar(255)                not null,
    size         bigint                      not null,
    storage      varchar(255)                not null
        constraint connector_message_attachments_storage_check
            check ((storage)::text = 'S3_BUCKET'::text),
    type         varchar(255)
        constraint connector_message_attachments_type_check
            check ((type)::text = ANY
                   ((ARRAY ['ATTACHMENT'::character varying, 'ASICS'::character varying, 'BUSINESS_CONTENT'::character varying, 'BUSINESS_DOCUMENT'::character varying, 'DETACHED_SIGNATURE'::character varying, 'EVIDENCE_XML'::character varying, 'PDF_TOKEN'::character varying, 'XML_TOKEN'::character varying])::text[])),
    message_id   bigint
        constraint fk2p3mqcv3o24e94ngrm3lgppm1
            references connector_messages
);

alter table connector_message_attachments
    owner to connector;

create table connector_message_business_contents
(
    id            bigint generated by default as identity
        primary key,
    created_at    timestamp(6) with time zone not null,
    updated_at    timestamp(6) with time zone not null,
    uuid          varchar(255)                not null
        constraint ukpt6k5iywuwh9uy4mxuh9xs6jg
            unique,
    message_id    bigint                      not null
        constraint ukbxhk118v0541xmdd7ixts5kdi
            unique
        constraint fk2jh116b11s4cr5788pmnsit4q
            references connector_messages,
    attachment_id bigint                      not null
        constraint ukal934nq46hlifnrn8bjq1boa0
            unique
        constraint fk40gtdmg3v5o97xy94frhhtwt
            references connector_message_attachments
);

alter table connector_message_business_contents
    owner to connector;

create table connector_message_business_documents
(
    id                  bigint generated by default as identity
        primary key,
    created_at          timestamp(6) with time zone not null,
    updated_at          timestamp(6) with time zone not null,
    aes_type            varchar(255)
        constraint connector_message_business_documents_aes_type_check
            check ((aes_type)::text = ANY
                   ((ARRAY ['AUTHENTICATION_BASED'::character varying, 'SIGNATURE_BASED'::character varying])::text[])),
    uuid                varchar(255)                not null
        constraint uke3edkhmc1qbmtwx4c5ggclvah
            unique,
    attachment_id       bigint                      not null
        constraint uk65cpf4kjdovq65tbq48t5eprf
            unique
        constraint fk8br14reyq9odt8xiddk5l9bbn
            references connector_message_attachments,
    business_content_id bigint                      not null
        constraint uka7dnlykk50vcil6l7fuo3gxkx
            unique
        constraint fkrqcpkxbe9fjrqa2if6gxhasiq
            references connector_message_business_contents
);

alter table connector_message_business_documents
    owner to connector;

create table connector_message_business_document_signatures
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6) with time zone not null,
    updated_at           timestamp(6) with time zone not null,
    mime_type            varchar(255)                not null
        constraint connector_message_business_document_signatures_mime_type_check
            check ((mime_type)::text = ANY
                   ((ARRAY ['BINARY'::character varying, 'XML'::character varying, 'PKCS7'::character varying])::text[])),
    name                 varchar(255)                not null,
    signature            bytea                       not null,
    uuid                 varchar(255)                not null
        constraint uk8agxfbqui5o0nbrqwve6lciw1
            unique,
    business_document_id bigint                      not null
        constraint ukgv33cadw3gesixne6mnfbagon
            unique
        constraint fk4ips0utvql5lind3yd3sfgsak
            references connector_message_business_documents
);

alter table connector_message_business_document_signatures
    owner to connector;

create table connector_message_errors
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone not null,
    updated_at timestamp(6) with time zone not null,
    details    varchar(255),
    label      varchar(255),
    source     varchar(255)                not null,
    message_id bigint                      not null
        constraint ukarhi6ty11tag5u92q1bcnu352
            unique
        constraint fkk1rsqfg9r8mptygobt5i35r1y
            references connector_messages
);

alter table connector_message_errors
    owner to connector;

create table connector_message_evidences
(
    id                           bigint generated by default as identity
        primary key,
    created_at                   timestamp(6) with time zone not null,
    updated_at                   timestamp(6) with time zone not null,
    content                      varchar(10000000),
    delivered_to_link_partner_at timestamp(6) with time zone,
    type                         varchar(255)                not null
        constraint connector_message_evidences_type_check
            check ((type)::text = ANY
                   ((ARRAY ['SUBMISSION_ACCEPTANCE'::character varying, 'SUBMISSION_REJECTION'::character varying, 'RELAY_REMMD_ACCEPTANCE'::character varying, 'RELAY_REMMD_REJECTION'::character varying, 'RELAY_REMMD_FAILURE'::character varying, 'DELIVERY'::character varying, 'NON_DELIVERY'::character varying, 'RETRIEVAL'::character varying, 'NON_RETRIEVAL'::character varying])::text[])),
    uuid                         varchar(255)                not null
        constraint ukelxrnuc4ssw3t7phloahld1ty
            unique,
    message_id                   bigint
        constraint fkp2bdwb4xr1kc9ibgv7dkrtimf
            references connector_messages
);

alter table connector_message_evidences
    owner to connector;

create table connector_processing_modes
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    content            varchar(10000000)           not null,
    description        varchar(255)                not null,
    filename           varchar(255)                not null,
    uuid               varchar(255)                not null
        constraint ukan0eybvhh8000jplnwehvloqr
            unique,
    business_domain_id bigint                      not null
        constraint fk2cwynu0uvtyud1y5t8olukdj4
            references connector_business_domains
);

alter table connector_processing_modes
    owner to connector;

create table connector_actions
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    name               varchar(255)                not null,
    uuid               varchar(255)                not null
        constraint ukjnbbwq3q6ly14mcfxby4ax7lw
            unique,
    processing_mode_id bigint                      not null
        constraint fknc17v09yjfh75xqgkv3165s94
            references connector_processing_modes
);

alter table connector_actions
    owner to connector;

create table connector_parties
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    identifier         varchar(255)                not null,
    identifier_type    varchar(255)                not null,
    is_home            boolean,
    name               varchar(255)                not null,
    role               varchar(255)                not null,
    role_type          varchar(255)                not null
        constraint connector_parties_role_type_check
            check ((role_type)::text = ANY
                   ((ARRAY ['INITIATOR'::character varying, 'RESPONDER'::character varying])::text[])),
    uuid               varchar(255)                not null
        constraint uk555wod80p30wb11ohae3cs60g
            unique,
    processing_mode_id bigint                      not null
        constraint fkayi25j0b3fvbdli0c5iwbo3n
            references connector_processing_modes
);

alter table connector_parties
    owner to connector;

create table connector_services
(
    id                 bigint generated by default as identity
        primary key,
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    name               varchar(255)                not null,
    type               varchar(255)                not null,
    uuid               varchar(255)                not null
        constraint uks6bnkkagws812cm80fnqqssb6
            unique,
    processing_mode_id bigint                      not null
        constraint fkdrgiyb2sv0d5yvdiknhmng7bg
            references connector_processing_modes
);

alter table connector_services
    owner to connector;

create table connector_message_as4_properties
(
    id                      bigint generated by default as identity
        primary key,
    created_at              timestamp(6) with time zone not null,
    updated_at              timestamp(6) with time zone not null,
    conversation_identifier varchar(255),
    ebms_message_identifier varchar(255),
    final_recipient         varchar(255)                not null,
    original_sender         varchar(255)                not null,
    reference_to_identifier varchar(255),
    action_id               bigint                      not null
        constraint fknahunyl5ry75t6dfbv5b8p9ty
            references connector_actions,
    from_party_id           bigint                      not null
        constraint fkjrt8qyo6gjb9iufmvfqd6bns3
            references connector_parties,
    message_id              bigint                      not null
        constraint uko99vlibfh8nr9m7ykgveia1yb
            unique
        constraint fkm1cypu5jqljrss1l35ll3xj7u
            references connector_messages,
    service_id              bigint                      not null
        constraint fk3fth7l1bm4xnlrxb58jsbu3oi
            references connector_services,
    to_party_id             bigint                      not null
        constraint fkkxtry3do0sru52ulipuhlaj7
            references connector_parties
);

alter table connector_message_as4_properties
    owner to connector;

