insert into connector_message_transport_step_statuses (
    status,
    created_at,
    updated_at,
    transport_step_id
)
values (
           'SUBMITTED',
           now(),
           now(),
           1
       ),
       (
           'READY_FOR_DOWNLOAD',
           now(),
           now(),
           2
       ),
       (
           'READY_FOR_DOWNLOAD',
           now(),
           now(),
           3
       ),
       (
           'DOWNLOADED',
           now(),
           now(),
           3
       );
