insert into connector_messages (id, backend_message_identifier,
                                          backend_name, confirmed_at, deleted_at,
                                          delivered_to_backend_at, delivered_to_gateway_at,
                                          direction, gateway_name, identifier,
                                          reference_to_backend_message_identifier, rejected_at,
                                          business_domain_id, created_at, updated_at)
values (1,
        'ec46d3f2-2efb-4d1c-b357-8bb7b4deb115',
        null,
        null,
        null,
        null,
        null,
        'BACKEND_TO_GATEWAY',
        null,
        'fd2f35e0-1981-4d21-b718-10a802e884b0@connector.ecodex.eu',
        null,
        null,
        1,
        now(),
        now()
       );
