on:
    push:
    pull_request:
    merge_group:
name: CI Pipeline
jobs:
    ci:
        uses: e-CODEX/workflows/.github/workflows/gradle-ci.yaml@8fe7dfab4831dddc935e4375c7aa24109cde97ed
        with:
            java-version: 21
            sbom-path: 'build/reports/cyclonedx/bom.xml'
