on:
    push:
    pull_request:
    merge_group:
name: CI Pipeline
jobs:
    ci:
        uses: e-CODEX/workflows/.github/workflows/gradle-ci.yaml@980ac49b3c61d0938d130d88ccfc543f26fa9bc1
        with:
            java-version: 21
            sbom-path: 'build/reports/cyclonedx/bom.xml'
