name: Manual Release Workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to deploy to'
                required: true
                default: 'production'
                type: choice
                options:
                    - production
jobs:
    check-version:
        name: Check the current release version
        uses: e-CODEX/workflows/.github/workflows/gradle-validate-release-version.yaml@73ed78c2786df167cc8b35afc8381436a560d581
    tag-version:
        name: Tag the current release version
        needs: check-version
        uses: e-CODEX/workflows/.github/workflows/gradle-tag-release-version.yaml@73ed78c2786df167cc8b35afc8381436a560d581
        with:
            environment: ${{ inputs.environment }}
    publish:
        name: Publish the current release version
        uses: e-CODEX/workflows/.github/workflows/gradle-publish-release.yaml@73ed78c2786df167cc8b35afc8381436a560d581
        needs: tag-version
        with:
            java-version: 21
            maven-repo-id: 'releases'
            gradle-parameters: '-Partifactory.repo.id=releases'
            tag: ${{ needs.tag-version.outputs.tag }}
            environment: ${{ inputs.environment }}
    docker:
        name: Build and push the docker image
        needs: tag-version
        uses: e-CODEX/workflows/.github/workflows/docker-build-push.yaml@main
        with:
            image-name: connector-ng
            tag: ${{ needs.tag-version.outputs.tag }}
            environment: ${{ inputs.environment }}
